import React from 'react';
import { motion } from 'framer-motion';
import { Zap, ArrowLeft, Shield, Info, HelpCircle, MessageSquare } from 'lucide-react';
import { Button } from '@/components/ui';

export type InfoTopic = 'terms' | 'privacy' | 'faq' | 'help';

interface InfoPageProps {
    topic: InfoTopic;
    onBack: () => void;
}

export const InfoPage: React.FC<InfoPageProps> = ({ topic, onBack }) => {
    const getContent = () => {
        switch (topic) {
            case 'terms':
                return {
                    title: 'Terms of Protocol',
                    subtitle: 'Legal Governance V3.0',
                    icon: <Shield className="text-[#0f62fe]" size={32} />,
                    sections: [
                        { title: '01. Agreement', content: 'By initializing the Brand OS DNA Protocol, you enter into a binding agreement with DNA Systems Global.' },
                        { title: '02. Data Usage', content: 'Brand DNA assets uploaded are encrypted and used solely for the training of your private brand models.' },
                        { title: '03. Intellectual Property', content: 'All outputs generated by the protocol are the sole property of the initiating entity, provided compliance rules are followed.' }
                    ]
                };
            case 'privacy':
                return {
                    title: 'Privacy Shield',
                    subtitle: 'Data Integrity Standards',
                    icon: <Shield className="text-[#f1c21b]" size={32} />,
                    sections: [
                        { title: '01. Zero-Knowledge', content: 'Our systems use zero-knowledge proofs for brand identity validation where possible.' },
                        { title: '02. Storage Protocol', content: 'DNA assets are stored in high-security, distributed nodes with 256-bit AES encryption.' },
                        { title: '03. No Drift', content: 'We do not sell your brand data to third-party model aggregators. Your DNA stays yours.' }
                    ]
                };
            case 'faq':
                return {
                    title: 'Q&A System',
                    subtitle: 'Operational Insights',
                    icon: <MessageSquare className="text-[#0f62fe]" size={32} />,
                    sections: [
                        { title: 'How many assets do I need?', content: 'The protocol requires a minimum of 5 high-fidelity assets to initialize the DNA sequence.' },
                        { title: 'What is "Brand Drift"?', content: 'Brand Drift occurs when AI outputs slowly deviate from original guidelines. Brand OS eliminates this via real-time enforcement.' },
                        { title: 'Is this for agencies or brands?', content: 'Both. Agencies use it for high-velocity governance; Brands use it for total control over their identity in the AI era.' }
                    ]
                };
            case 'help':
                return {
                    title: 'Support Node',
                    subtitle: 'Technical Assistance',
                    icon: <HelpCircle className="text-[#f1c21b]" size={32} />,
                    sections: [
                        { title: 'Documentation', content: 'Access the full Brand OS operational manual via the "Docs" command in the system console.' },
                        { title: 'Direct Uplink', content: 'Enterprise users have access to 24/7 dedicated brand engineers for protocol optimization.' },
                        { title: 'Audit Failure?', content: 'If an audit fails, check your "Grammar Rules" in the Doctrine module for conflicting constraints.' }
                    ]
                };
            default:
                return { title: 'Unknown Page', subtitle: 'Error', icon: <Info />, sections: [] };
        }
    };

    const content = getContent();

    return (
        <div className="min-h-screen bg-[#000000] text-[#f4f4f4] relative overflow-hidden flex flex-col pt-32 px-8 pb-32">
            <div className="cinematic-noise" />
            <div className="absolute inset-0 z-0 opacity-[0.05] pointer-events-none"
                style={{
                    backgroundImage: 'linear-gradient(#fff 1px, transparent 1px), linear-gradient(90deg, #fff 1px, transparent 1px)',
                    backgroundSize: '100px 100px'
                }} />

            <div className="max-w-[1200px] mx-auto w-full relative z-10 flex-1">
                <Button
                    onClick={onBack}
                    variant="ghost"
                    className="mb-16 -ml-4 hover:bg-white/5 text-[#525252] hover:text-white uppercase tracking-[0.3em] font-black text-[10px] gap-3"
                >
                    <ArrowLeft size={16} /> [ Back_to_Interface ]
                </Button>

                <motion.div
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
                >
                    <div className="flex items-center gap-6 mb-12">
                        <div className="w-16 h-16 bg-[#161616] border border-[#393939] flex items-center justify-center aura-glow">
                            {content.icon}
                        </div>
                        <div>
                            <div className="text-[10px] font-black text-[#525252] uppercase tracking-[0.4em] mb-2 font-mono">
                                [ {content.subtitle} ]
                            </div>
                            <h1 className="text-[clamp(3rem,8vw,10rem)] font-black tracking-tighter uppercase leading-none">
                                {content.title}
                            </h1>
                        </div>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-px bg-[#393939] border border-[#393939] mt-24">
                        {content.sections.map((section, i) => (
                            <div key={i} className="p-12 bg-black hover:bg-[#0a0a0a] transition-colors group">
                                <div className="text-[10px] font-black text-[#f1c21b] uppercase tracking-[0.3em] mb-8 font-mono">NODE_0{i + 1}</div>
                                <h2 className="text-3xl font-black uppercase mb-6 tracking-tighter group-hover:translate-x-1 transition-transform">{section.title}</h2>
                                <p className="text-xl text-[#c6c6c6] font-light leading-relaxed">{section.content}</p>
                            </div>
                        ))}
                    </div>

                    <div className="mt-24 p-12 bg-[#0f62fe] text-white">
                        <h3 className="text-2xl font-black uppercase mb-6 tracking-tighter">Need more precision?</h3>
                        <p className="text-xl font-light mb-12 opacity-90 max-w-2xl">
                            Our team of brand engineers is available for deep protocol integration and custom governance setups.
                        </p>
                        <Button className="bg-white text-[#0f62fe] hover:bg-white/90 rounded-none font-black uppercase tracking-widest px-12 h-16">
                            Contact Engineering
                        </Button>
                    </div>
                </motion.div>
            </div>

            <footer className="mt-auto pt-32 max-w-[1200px] mx-auto w-full flex justify-between items-center text-[10px] font-mono text-[#333] font-black tracking-[0.4em] uppercase border-t border-[#1a1a1a]">
                <span>© 2026 DNA_SYSTEMS_GLOBAL</span>
                <span>Security_Status: [ PROTECTED ]</span>
            </footer>
        </div>
    );
};
