import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Zap, ArrowLeft, Shield, Info, HelpCircle, MessageSquare, ChevronDown, Check, X, FileText, Cookie, Database } from 'lucide-react';
import { Button } from '@/components/ui';

export type InfoTopic = 'terms' | 'privacy' | 'cookies' | 'licenses' | 'faq' | 'help';

interface InfoPageProps {
    topic: InfoTopic;
    onBack: () => void;
}

export const InfoPage: React.FC<InfoPageProps> = ({ topic, onBack }) => {
    // Accordion State for Terms/Privacy
    const [openSection, setOpenSection] = useState<number | null>(0);

    // Toggle State for Cookies
    const [cookiePrefs, setCookiePrefs] = useState({
        essential: true,
        analytics: true,
        marketing: false
    });

    interface InfoContent {
        title: string;
        subtitle: string;
        icon: React.ReactNode;
        desc?: string;
        interactiveElement?: React.ReactNode;
    }

    const getContent = (): InfoContent => {
        switch (topic) {
            case 'terms':
                return {
                    title: 'Terms of Protocol',
                    subtitle: 'Legal Governance V3.0',
                    icon: <Shield className="text-[#0f62fe]" size={32} />,
                    desc: 'By initializing the Brand OS DNA Protocol, you enter into a binding agreement with DNA Systems Global. Usage is monitored for compliance.',
                    interactiveElement: (
                        <div className="border border-[#393939] bg-[#161616]">
                            {[
                                { title: '01. LICENSE GRANT', content: 'Subject to the terms of this Agreement, Brand OS grants you a limited, non-exclusive, non-transferable license to use the Protocol. You may not sublicense, lease, or rent the Protocol to any third party.' },
                                { title: '02. PROHIBITED USES', content: 'You may not use the Protocol to generate content that violates applicable laws, constitutes hate speech, or infringes on third-party intellectual property. Violation results in immediate token revocation.' },
                                { title: '03. INTELLECTUAL PROPERTY', content: 'All model weights and fine-tuned checkpoints generated by your usage of the Protocol remain your sole property. DNA Systems Global claims zero ownership over your generated assets.' },
                                { title: '04. TERMINATION', content: 'We reserve the right to terminate your access to the Protocol if we detect any "Brand Drift" exceeding 40% (negligence) or malicious use of the generative engine.' }
                            ].map((item, i) => (
                                <div key={i} className="border-b border-[#393939] last:border-0">
                                    <button
                                        onClick={() => setOpenSection(openSection === i ? null : i)}
                                        className="w-full flex items-center justify-between p-6 hover:bg-[#262626] transition-colors text-left group"
                                    >
                                        <span className="text-sm font-black uppercase tracking-widest text-[#f4f4f4] group-hover:text-[#0f62fe] transition-colors">{item.title}</span>
                                        <ChevronDown size={16} className={`text-[#666] transition-transform duration-300 ${openSection === i ? 'rotate-180' : ''}`} />
                                    </button>
                                    <AnimatePresence>
                                        {openSection === i && (
                                            <motion.div
                                                initial={{ height: 0, opacity: 0 }}
                                                animate={{ height: 'auto', opacity: 1 }}
                                                exit={{ height: 0, opacity: 0 }}
                                                className="overflow-hidden"
                                            >
                                                <div className="p-6 pt-0 text-[#c6c6c6] font-mono text-sm leading-relaxed border-t border-[#393939] border-dashed">
                                                    {item.content}
                                                </div>
                                            </motion.div>
                                        )}
                                    </AnimatePresence>
                                </div>
                            ))}
                        </div>
                    )
                };
            case 'privacy':
                return {
                    title: 'Privacy Shield',
                    subtitle: 'Data Integrity Standards',
                    icon: <LockIcon className="text-[#f1c21b]" size={32} />, // Helper component usage below
                    desc: 'We use zero-knowledge proofs for brand identity validation. Your visual tokens are never exposed to the public chain.',
                    interactiveElement: (
                        <div className="border border-[#393939] bg-[#161616]">
                            {[
                                { title: 'DATA COLLECTION', content: 'We collect only the visual tokens and "vibe" metadata required to train your specific model. No PII is stored on our training clusters.' },
                                { title: 'MODEL ISOLATION', content: 'Your brand model is air-gapped from other tenants. We do not use your data to train a foundational model. Ops are isolated via containerization.' },
                                { title: 'RETENTION POLICY', content: 'You may request a "Protocol Wipe" at any time, which cryptographically shreds your model weights and source assets from our hot storage.' }
                            ].map((item, i) => (
                                <div key={i} className="border-b border-[#393939] last:border-0">
                                    <div className="p-6">
                                        <h3 className="text-sm font-black uppercase tracking-widest text-[#f1c21b] mb-4">{item.title}</h3>
                                        <p className="text-[#c6c6c6] font-mono text-sm leading-relaxed">{item.content}</p>
                                    </div>
                                </div>
                            ))}
                        </div>
                    )
                };
            case 'cookies':
                return {
                    title: 'Tracking Nodes',
                    subtitle: 'Preference Center',
                    icon: <Cookie className="text-[#0f62fe]" size={32} />,
                    desc: 'Control how our system interacts with your local storage. We default to minimal retention.',
                    interactiveElement: (
                        <div className="border border-[#393939] bg-[#161616] p-8 space-y-8">
                            {[
                                { id: 'essential', label: 'Essential Nodes', desc: 'Required for auth tokens and session integrity.', protected: true },
                                { id: 'analytics', label: 'Telemetry (Analytics)', desc: 'Helps us optimize system latencies and load balancing.', protected: false },
                                { id: 'marketing', label: 'Signal Boost (Marketing)', desc: 'Personalized feature reduction based on usage patterns.', protected: false }
                            ].map((cookie, i) => (
                                <div key={i} className="flex items-start justify-between group">
                                    <div className="max-w-xl">
                                        <div className="flex items-center gap-3 mb-2">
                                            <div className={`w-2 h-2 rounded-full ${cookiePrefs[cookie.id as keyof typeof cookiePrefs] ? 'bg-[#24a148]' : 'bg-[#393939]'}`} />
                                            <h3 className="text-lg font-bold uppercase tracking-wider">{cookie.label}</h3>
                                        </div>
                                        <p className="text-[#999] font-mono text-xs pl-5 leading-relaxed">{cookie.desc}</p>
                                    </div>
                                    <div className="relative">
                                        {cookie.protected ? (
                                            <div className="text-[10px] font-black uppercase tracking-[0.2em] text-[#666] py-2 px-4 border border-[#393939] bg-[#262626]">
                                                [ LOCKED ]
                                            </div>
                                        ) : (
                                            <button
                                                onClick={() => setCookiePrefs(prev => ({ ...prev, [cookie.id]: !prev[cookie.id as keyof typeof cookiePrefs] }))}
                                                className={`w-12 h-6 rounded-full p-1 transition-colors duration-300 ${cookiePrefs[cookie.id as keyof typeof cookiePrefs] ? 'bg-[#0f62fe]' : 'bg-[#393939]'}`}
                                            >
                                                <div className={`w-4 h-4 rounded-full bg-white shadow-md transform transition-transform duration-300 ${cookiePrefs[cookie.id as keyof typeof cookiePrefs] ? 'translate-x-6' : 'translate-x-0'}`} />
                                            </button>
                                        )}
                                    </div>
                                </div>
                            ))}
                            <div className="pt-8 border-t border-[#393939]">
                                <Button className="w-full bg-[#f4f4f4] text-black hover:bg-white font-black uppercase tracking-widest h-12 rounded-none">
                                    Save_Preferences
                                </Button>
                            </div>
                        </div>
                    )
                };
            case 'licenses':
                return {
                    title: 'OSS_ATTRIBUTION',
                    subtitle: 'Open Source Ledger',
                    icon: <Database className="text-[#f1c21b]" size={32} />,
                    desc: 'We stand on the shoulders of giants. Below is a ledger of the open source technologies that power the Brand OS protocol.',
                    interactiveElement: (
                        <div className="bg-[#1e1e1e] border border-[#393939] overflow-hidden">
                            <table className="w-full text-left font-mono text-xs">
                                <thead className="bg-[#2d2d2d] text-[#c6c6c6]">
                                    <tr>
                                        <th className="p-4 uppercase tracking-wider font-bold">Library</th>
                                        <th className="p-4 uppercase tracking-wider font-bold">License</th>
                                        <th className="p-4 uppercase tracking-wider font-bold">Version</th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y divide-[#393939] text-[#999]">
                                    <tr><td className="p-4 text-white">React</td><td className="p-4">MIT</td><td className="p-4">v18.2</td></tr>
                                    <tr><td className="p-4 text-white">Framer Motion</td><td className="p-4">MIT</td><td className="p-4">v10.12</td></tr>
                                    <tr><td className="p-4 text-white">Lucide</td><td className="p-4">ISC</td><td className="p-4">v0.263</td></tr>
                                    <tr><td className="p-4 text-white">Tailwind CSS</td><td className="p-4">MIT</td><td className="p-4">v3.3</td></tr>
                                    <tr><td className="p-4 text-white">Vite</td><td className="p-4">MIT</td><td className="p-4">v4.4</td></tr>
                                    <tr><td className="p-4 text-white">TypeScript</td><td className="p-4">Apache 2.0</td><td className="p-4">v5.0</td></tr>
                                </tbody>
                            </table>
                        </div>
                    )
                };
            case 'faq':
                return {
                    title: 'Q&A System',
                    subtitle: 'Operational Insights',
                    icon: <MessageSquare className="text-[#0f62fe]" size={32} />,
                    desc: 'Common queries regarding protocol operation, billing cycles, and enterprise integration.',
                    interactiveElement: (
                        <div className="bg-[#161616] border border-[#393939] p-8">
                            <div className="grid gap-8">
                                {[
                                    { q: 'How many assets do I need?', a: 'The protocol requires a minimum of 5 high-fidelity assets to initialize the DNA sequence.' },
                                    { q: 'What is "Brand Drift"?', a: 'Brand Drift occurs when AI outputs slowly deviate from original guidelines. Brand OS eliminates this via real-time enforcement.' },
                                    { q: 'Is this for agencies or brands?', a: 'Both. Agencies use it for high-velocity governance; Brands use it for total control over their identity in the AI era.' }
                                ].map((item, i) => (
                                    <div key={i}>
                                        <h3 className="text-lg font-bold text-white mb-2">{item.q}</h3>
                                        <p className="text-[#999] font-mono text-sm leading-relaxed">{item.a}</p>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )
                };
            case 'help':
                return {
                    title: 'Support Node',
                    subtitle: 'Technical Assistance',
                    icon: <HelpCircle className="text-[#f1c21b]" size={32} />,
                    desc: 'Direct uplink to our engineering team.',
                    interactiveElement: (
                        <div className="bg-[#161616] border border-[#393939] p-12 text-center">
                            <div className="w-16 h-16 bg-[#333] rounded-full flex items-center justify-center mx-auto mb-6">
                                <Zap className="text-[#f1c21b]" size={32} />
                            </div>
                            <h3 className="text-2xl font-black uppercase mb-4">Priority Uplink</h3>
                            <p className="text-[#999] max-w-md mx-auto mb-8 font-light">
                                Enterprise users have access to 24/7 dedicated brand engineers. Average response time is under 15 minutes.
                            </p>
                            <Button className="bg-[#0f62fe] text-white hover:bg-[#0353e9] h-12 px-8 font-black uppercase tracking-widest rounded-none">
                                Open_Ticket
                            </Button>
                        </div>
                    )
                };
            default:
                return { title: 'Unknown Page', subtitle: 'Error', icon: <Info />, desc: '', interactiveElement: null };
        }
    };

    const content = getContent();

    // Helper component for Icon
    function LockIcon(props: any) { return <Shield {...props} />; }

    return (
        <div className="min-h-screen bg-[#000000] text-[#f4f4f4] relative overflow-hidden flex flex-col pt-32 px-8 pb-32">
            <div className="cinematic-noise" />
            <div className="absolute inset-0 z-0 opacity-[0.05] pointer-events-none"
                style={{
                    backgroundImage: 'linear-gradient(#fff 1px, transparent 1px), linear-gradient(90deg, #fff 1px, transparent 1px)',
                    backgroundSize: '100px 100px'
                }} />

            <div className="max-w-[1200px] mx-auto w-full relative z-10 flex-1">
                <Button
                    onClick={onBack}
                    variant="ghost"
                    className="mb-16 -ml-4 hover:bg-white/5 text-[#525252] hover:text-white uppercase tracking-[0.3em] font-black text-[10px] gap-3"
                >
                    <ArrowLeft size={16} /> [ Back_to_Interface ]
                </Button>

                <motion.div
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
                >
                    <div className="flex items-center gap-6 mb-12">
                        <div className="w-16 h-16 bg-[#161616] border border-[#393939] flex items-center justify-center aura-glow">
                            {content.icon}
                        </div>
                        <div>
                            <div className="text-[10px] font-black text-[#525252] uppercase tracking-[0.4em] mb-2 font-mono">
                                [ {content.subtitle} ]
                            </div>
                            <h1 className="text-[clamp(3rem,8vw,10rem)] font-black tracking-tighter uppercase leading-none">
                                {content.title}
                            </h1>
                        </div>
                    </div>

                    <p className="text-xl text-[#c6c6c6] font-light leading-relaxed max-w-3xl mb-16 border-l-2 border-[#393939] pl-6">
                        {content.desc}
                    </p>

                    {content.interactiveElement && (
                        <div className="mt-12 w-full">
                            {content.interactiveElement}
                        </div>
                    )}
                </motion.div>
            </div>

            <footer className="mt-auto pt-32 max-w-[1200px] mx-auto w-full flex justify-between items-center text-[10px] font-mono text-[#333] font-black tracking-[0.4em] uppercase border-t border-[#1a1a1a]">
                <span>© 2026 DNA_SYSTEMS_GLOBAL</span>
                <span>Security_Status: [ PROTECTED ]</span>
            </footer>
        </div>
    );
};
